# Data split ratios
train_ratio: 0.8
val_ratio: 0.1
test_ratio: 0.1


# Training parameters
models:
  svm:
    C: 1.6
    kernel: "rbf"
    gamma: "scale"
    class_weight: "balanced"
    probability: True
    random_state: 0

  random_forest:
    # Optuna tuning
    placeholder: True

  lightgbm:
    # Optuna tuning
    placeholder: True
